name = "mcdaba"
author = "daba2iki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8623701f0135e429ca44591236c22dc279e5061ec99f1037f581b4f3be6387e8"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
