name = "mcdaba"
author = "daba2iki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "755feb2e79271be50024a6b5f4774f8d5b6c581483a209a2a5c77c5cabd222ab"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
acceptable-game-versions = ["1.20.1"]
