name = "mcdaba"
author = "daba2iki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1bb3de6fa07e77d6318a4ffed1e6c3276cbc24333da46b847d1ef2d63d8018a"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
